spring:
  application:
    name: DevOpsInvestigation
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/Users/lari/IdeaProjects/women_reboot/users.db
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true